apiVersion: v1
kind: Namespace
metadata:
  name: myapp
---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "test"
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "pass"
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: myapp
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
---
# MyApp Deployment (v1)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
      - name: myapp
        image: dmitriizolotov/demoapp:v3
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://user:pass@postgresql:5432/test"
---
# MyApp Service
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: myapp
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: myapp
